### ISSUE TITLE
样式怎么修改

### ISSUE THREAD

**Issue by jianchenc** [yujinpan/el-select-tree#38]
下来树样式怎么修改

**Comment by yujinpan** [comment]
```scss
.el-select-tree {
   .el-tree {
     // your tree style
     color: red;
   }

   // if scoped
   ::v-deep {
     .el-tree {
       // your tree style
     }
   }
}
```
